name: deploy-web

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "16.x"
      - name: install deps
        run: npm install
      - name: build app
        run: npm run build
      - name: copy dist file with scp
        uses: appleboy/scp-action@v0.0.1
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          port: 22
          source: 'docs/'
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/dist/, /node_modules/"












